name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install webtui
        run: |
          curl -L https://github.com/webtui/webtui/releases/download/v0.9.2/webtui-linux-amd64 -o webtui
          chmod +x webtui
          sudo mv webtui /usr/local/bin/webtui

      - name: Check binary
        run: file /usr/local/bin/webtui

      - name: Build site
        run: webtui build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public